#!/bin/bash
. /home/youpot/youpot/utils/bin/activate
echo "launching ssh-mitm server  --store-ssh-session  --banner-name "SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u8" --listen-address 127.0.0.1 --session-log-dir  $1  --remote-host $2 --remote-port $3 --listen-port $4 > $1/ssh_mitm.log 2>&1" 

exec ssh-mitm server  --store-ssh-session --store-scp-files --store-command-data  --banner-name "SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u8" --listen-address 127.0.0.1 --session-log-dir  $1  --remote-host $2 --remote-port $3 --listen-port $4 > $1/ssh_mitm.log 2>&1 
